# Generated by Django 5.2.15 on 2026-06-16 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Spool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('material', models.CharField(max_length=50)),
                ('color_name', models.CharField(max_length=100)),
                ('color_hex', models.CharField(max_length=7)),
                ('full_weight_g', models.PositiveIntegerField()),
                ('remaining_g', models.FloatField()),
                ('price_paid', models.DecimalField(decimal_places=2, max_digits=8)),
                ('purchase_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['brand', 'color_name'],
            },
        ),
    ]
