# Generated by Django 5.2.15 on 2026-06-16 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('printed_at', models.DateTimeField()),
                ('source', models.CharField(choices=[('threemf', '3MF'), ('gcode', 'G-code'), ('manual', 'Manual'), ('script', 'Script')], max_length=20)),
                ('source_file', models.FileField(blank=True, upload_to='prints/')),
                ('source_url', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('pending_assignment', 'Pending Assignment'), ('confirmed', 'Confirmed')], default='pending_assignment', max_length=50)),
                ('queue_notes', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PrintSpool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grams_used', models.FloatField()),
                ('slicer_hex', models.CharField(blank=True, max_length=7)),
                ('print_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spools_used', to='tracker.printlog')),
                ('spool', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.spool')),
            ],
        ),
    ]
