# Generated by Django 5.2.15 on 2026-07-13 19:45

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_printlog_printspool'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilamentProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(db_index=True, max_length=100, unique=True)),
                ('brand', models.CharField(max_length=100)),
                ('material', models.CharField(max_length=50)),
                ('color_name', models.CharField(blank=True, max_length=100)),
                ('color_hex', models.CharField(default='#808080', max_length=7)),
                ('full_weight_g', models.PositiveIntegerField(default=1000)),
                ('diameter_mm', models.DecimalField(decimal_places=2, default=Decimal('1.75'), max_digits=4)),
            ],
            options={
                'ordering': ['brand', 'material', 'color_name'],
            },
        ),
        migrations.AddField(
            model_name='spool',
            name='diameter_mm',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.75'), max_digits=4),
        ),
        migrations.AddField(
            model_name='spool',
            name='sku',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
