# Generated by Django 5.2.15 on 2026-07-30 12:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_fk_cascade_postgres'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('item_description', models.CharField(max_length=200)),
                ('printer', models.CharField(blank=True, max_length=60)),
                ('filament_g', models.FloatField(default=0)),
                ('print_hours', models.FloatField(default=0)),
                ('material_cost', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('labor_cost', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('other_cost', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
